language: android
android:
    components:
        # The BuildTools version used by your project
        - build-tools-27.0.3
        # The SDK version used to compile your project
        - android-28
        # The SDK version used by the system image
        - android-22
        # The system image, to run an emulator during the tests
        - sys-img-armeabi-v7a-android-22
before_script: 
  # Set up Code Climate test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82
script:
  - chmod +x ./gradlew
  - ./gradlew build connectedCheck jacocoTestReport
after_script:
  # Report test coverage to Code Climate
  - export JACOCO_SOURCE_PATH=app/src/main/java/
  - ./cc-test-reporter format-coverage ./app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
